name: Build Portable FixAllTool (Single EXE)

on:
  push:
    tags: ['v*']         # builds when you publish a tag like v1.0.0
  workflow_dispatch:      # lets you run it manually

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show tree (debug)
        run: |
          dir
          dir .\Source
          dir .\Source\FixAllTool
          dir .\ai_service

      - name: Build ai_service.exe (PyInstaller)
        working-directory: ai_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile --name ai_service app.py
          New-Item -ItemType Directory -Path $Env:GITHUB_WORKSPACE\dist -Force | Out-Null
          Copy-Item .\dist\ai_service.exe $Env:GITHUB_WORKSPACE\dist -Force

      - name: Publish WPF single-file EXE
        run: |
          dotnet publish .\Source\FixAllTool\FixAllTool.csproj `
            -c Release -r win-x64 --self-contained true `
            /p:PublishSingleFile=true `
            /p:IncludeAllContentForSelfExtract=true `
            /p:DebugType=none /p:Optimize=true /p:ReadyToRun=true `
            /p:TieredCompilation=true /p:TieredPGO=true `
            -o .\publish\fixall_x64
          New-Item -ItemType Directory -Path .\dist -Force | Out-Null
          Copy-Item .\publish\fixall_x64\FixAllTool.exe .\dist\ -Force
          if (Test-Path .\Assets) { Copy-Item .\Assets .\dist\ -Recurse -Force }
          if (Test-Path .\Guides) { Copy-Item .\Guides .\dist\ -Recurse -Force }

      - name: Package portable ZIP
        run: |
          Compress-Archive -Path .\dist\* -DestinationPath .\FixAllTool_Portable.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FixAllTool_Portable
          path: FixAllTool_Portable.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FixAllTool_Portable
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: FixAllTool_Portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
