name: Build Portable FixAllTool (Single EXE)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show tree (debug)
        shell: pwsh
        run: |
          dir
          dir .\Source -ea 0
          dir .\Source\FixAllTool -ea 0
          dir .\ai_service -ea 0

      - name: Install Python deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path ai_service\requirements.txt) { pip install -r ai_service\requirements.txt }
          pip install pyinstaller

      - name: Build ai_service.exe
        shell: pwsh
        run: |
          if (Test-Path ai_service\app.py) { pyinstaller --onefile --name ai_service ai_service\app.py --distpath dist }

      - name: Publish WPF single-file EXE
        shell: pwsh
        run: |
          dotnet publish .\Source\FixAllTool\FixAllTool.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -o .\publish\fixall_x64
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          Copy-Item .\publish\fixall_x64\FixAllTool.exe .\dist\ -Force
          if (Test-Path .\Assets) { Copy-Item .\Assets .\dist\ -Recurse -Force }
          if (Test-Path .\Guides) { Copy-Item .\Guides .\dist\ -Recurse -Force }

      - name: Package portable ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path .\dist\* -DestinationPath .\FixAllTool_Portable.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FixAllTool_Portable
          path: FixAllTool_Portable.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: FixAllTool_Portable
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: FixAllTool_Portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
