name: Build Portable FixAllTool (Single EXE)

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  # Optional lint (runs on Linux; won't block Windows build if you remove 'needs')
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/build-release.yml
          format: standard
          strict: false  # set true to fail on style issues

  build:
    # if you keep lint, you can require it with: needs: lint
    runs-on: windows-latest
    defaults: { run: { shell: pwsh } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Show tree (debug)
        run: |
          dir
          dir .\Source -ea 0
          dir .\Source\FixAllTool -ea 0
          dir .\ai_service -ea 0

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path ai_service\requirements.txt) { pip install -r ai_service\requirements.txt }
          pip install pyinstaller

      - name: Build ai_service.exe
        run: |
          if (Test-Path ai_service\app.py) { pyinstaller --onefile --name ai_service ai_service\app.py --distpath dist }

      - name: Publish WPF single-file EXE
        run: |
          dotnet publish .\Source\FixAllTool\FixAllTool.csproj `
            -c Release -r win-x64 --self-contained true `
            /p:PublishSingleFile=true `
            /p:IncludeAllContentForSelfExtract=true `
            /p:DebugType=none /p:Optimize=true /p:ReadyToRun=true `
            /p:TieredCompilation=true /p:TieredPGO=true `
            -o .\publish\fixall_x64
          Copy-Item .\publish\fixall_x64\FixAllTool.exe .\dist\ -Force
          if (Test-Path .\Assets) { Copy-Item .\Assets .\dist\ -Recurse -Force }
          if (Test-Path .\Guides) { Copy-Item .\Guides .\dist\ -Recurse -Force }

      - name: Package portable ZIP
        run: Compress-Archive -Path .\dist\* -DestinationPath .\FixAllTool_Portable.zip -Force

      - uses: actions/upload-artifact@v4
        with:
          name: FixAllTool_Portable
          path: FixAllTool_Portable.zip
